import { collection, addDoc } from 'firebase/firestore';
import { db } from './firebase';

const sampleLeads = [
  {
    name: "Sarah Mitchell",
    email: "sarah.mitchell@email.com",
    phone: "(206) 555-1234",
    status: "Tour Completed",
    moveInDate: "2025-12-01",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "1 small dog (corgi)",
    notes: "Very interested in top floor unit. Works from home 3 days/week. Needs good lighting.",
    address: "4521 Pine St, Seattle, WA 98101",
    employer: "Microsoft",
    moveReason: "Upsizing"
  },
  {
    name: "Marcus Chen",
    email: "mchen92@email.com",
    phone: "(425) 555-5678",
    status: "Leased",
    moveInDate: "2025-01-15",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "None",
    notes: "Signed 12-month lease. Paid first, last, and deposit. Works at Amazon.",
    address: "8923 Bellevue Way, Bellevue, WA 98004",
    employer: "Amazon",
    moveReason: "Job Relocation"
  },
  {
    name: "Jennifer Davis",
    email: "jdavis.seattle@email.com",
    phone: "(206) 555-9012",
    status: "New Inquiry",
    moveInDate: "2025-11-11",
    unitType: "Studio",
    occupants: 1,
    pets: "2 cats",
    notes: "First-time renter, graduating from UW. Parent co-signer available.",
    address: "UW Dorms, Seattle, WA 98195",
    employer: "Graduate Student - UW",
    moveReason: "First Time Renter"
  },
  {
    name: "Ken Doll",
    email: "mymansion@email.com",
    phone: "(425) 986-1238",
    status: "Leased Elsewhere",
    moveInDate: "2025-12-31",
    unitType: "3 Bedroom",
    occupants: 4,
    pets: "None",
    notes: "Chose competitor property due to closer proximity to kids' school.",
    address: "7823 Malibu Dr, Kirkland, WA 98033",
    employer: "Boeing",
    moveReason: "Downsizing"
  },
  {
    name: "Ben Jamin",
    email: "beninseattle@email.com",
    phone: "(206) 555-0921",
    status: "Search Hold",
    moveInDate: "2026-05-01",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Waiting for current lease to end. Very price-conscious. Interested in any move-in specials.",
    address: "2341 Capitol Hill Ave, Seattle, WA 98122",
    employer: "Freelance Designer",
    moveReason: "Other"
  },
  {
    name: "Robert & Amy Johnson",
    email: "johnson.family@email.com",
    phone: "(425) 555-0154",
    status: "Tour Completed",
    moveInDate: "2025-03-01",
    unitType: "3 Bedroom",
    occupants: 4,
    pets: "1 golden retriever",
    notes: "Family of 4 (2 kids ages 8 and 12). Need ground floor, good schools nearby. Toured Unit 105.",
    address: "5612 Redmond Way, Redmond, WA 98052",
    employer: "T-Mobile / Seattle Children's Hospital",
    moveReason: "Upsizing"
  },
  {
    name: "Alex Rivera",
    email: "arivera.seattle@gmail.com",
    phone: "(206) 555-0121",
    status: "New Inquiry",
    moveInDate: "2025-02-15",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 cat",
    notes: "Prefers units with balcony. Flexible on move-in date. Works night shifts.",
    address: "3421 Aurora Ave N, Seattle, WA 98103",
    employer: "Swedish Medical Center",
    moveReason: "Closer to Work"
  },
  {
    name: "David Park",
    email: "dpark89@outlook.com",
    phone: "(425) 555-0189",
    status: "Contacted",
    moveInDate: "2025-01-30",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "None",
    notes: "Moving in with partner. Both work in tech. Interested in parking availability.",
    address: "9821 Lake City Way, Seattle, WA 98125",
    employer: "Meta",
    moveReason: "Job Relocation"
  },
  {
    name: "Lisa Thompson",
    email: "lisa.thompson@uw.edu",
    phone: "(206) 555-0167",
    status: "Leased",
    moveInDate: "2024-12-01",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Current resident since Dec 1. Excellent payment history. Studying medicine at UW.",
    address: "Unit 203, Your Building",
    employer: "UW Medical Resident",
    moveReason: "First Time Renter"
  },
  // Adding a few more for variety
  {
    name: "Emily Rodriguez",
    email: "emily.r@gmail.com",
    phone: "(206) 555-0143",
    status: "Application Submitted",
    moveInDate: "2025-01-20",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 rabbit",
    notes: "Application pending background check. Excellent credit score 780+. References checked.",
    address: "6734 Greenwood Ave, Seattle, WA 98103",
    employer: "Starbucks Corporate",
    moveReason: "Downsizing"
  },
  {
    name: "Michael Foster",
    email: "mfoster2025@outlook.com",
    phone: "(425) 555-0198",
    status: "Tour Scheduled",
    moveInDate: "2025-02-01",
    unitType: "2 Bedroom",
    occupants: 3,
    pets: "2 small dogs",
    notes: "Tour scheduled for this Saturday 2pm. Bringing roommates. Need 2 parking spots.",
    address: "4521 Bothell Way, Bothell, WA 98011",
    employer: "Boeing",
    moveReason: "Closer to Work"
  },
  {
    name: "Christina Lee",
    email: "clee.seattle@gmail.com",
    phone: "(206) 555-0176",
    status: "Approved",
    moveInDate: "2025-01-25",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Approved! Waiting for lease signing appointment. Wants Unit 308 specifically.",
    address: "8234 University Way, Seattle, WA 98105",
    employer: "Google",
    moveReason: "Job Relocation"
  },
  {
    name: "Daniel Kim",
    email: "dkim.tech@gmail.com",
    phone: "(425) 555-0201",
    status: "New Inquiry",
    moveInDate: "2025-03-15",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 parrot",
    notes: "Software engineer seeking quiet unit for remote work. Concerned about noise levels. Has an African Grey parrot.",
    address: "1234 Tech Plaza, Redmond, WA 98052",
    employer: "Oracle",
    moveReason: "Closer to Work"
  },
  {
    name: "Rachel Green",
    email: "rgreen.fashion@outlook.com",
    phone: "(206) 555-0212",
    status: "Tour Completed",
    moveInDate: "2025-02-28",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "1 hairless cat",
    notes: "Fashion designer needs good natural light for home studio. Partner is a chef, interested in kitchen quality.",
    address: "5678 Broadway E, Seattle, WA 98102",
    employer: "Nordstrom",
    moveReason: "Upsizing"
  },
  {
    name: "James Wilson",
    email: "jwilson.md@hospital.com",
    phone: "(206) 555-0223",
    status: "Contacted",
    moveInDate: "2025-04-01",
    unitType: "3 Bedroom",
    occupants: 3,
    pets: "2 large dogs",
    notes: "Doctor with rotating shifts. Needs 24/7 access. Has two German Shepherds, needs ground floor with yard access.",
    address: "9012 Medical Center Way, Seattle, WA 98109",
    employer: "Harborview Medical Center",
    moveReason: "Pet-Friendly Housing"
  },
  {
    name: "Monica Patel",
    email: "mpatel.startup@gmail.com",
    phone: "(425) 555-0234",
    status: "Application Submitted",
    moveInDate: "2025-01-31",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Startup founder, may need flexible lease terms. Strong financials but irregular income. Has investor backing letter.",
    address: "3456 Innovation Dr, Bellevue, WA 98005",
    employer: "Self-Employed (TechStart Inc)",
    moveReason: "Downsizing"
  },
  {
    name: "Kevin O'Brien",
    email: "kobrien.music@gmail.com",
    phone: "(206) 555-0245",
    status: "Tour Scheduled",
    moveInDate: "2025-02-15",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 snake",
    notes: "Professional musician, tours frequently. Needs secure unit, concerned about instrument storage. Has a ball python in terrarium.",
    address: "7890 Pike St, Seattle, WA 98122",
    employer: "Seattle Symphony",
    moveReason: "Other"
  },
  {
    name: "Amanda Zhang",
    email: "azhang.law@legalfirm.com",
    phone: "(206) 555-0256",
    status: "Leased",
    moveInDate: "2024-11-15",
    unitType: "2 Bedroom",
    occupants: 1,
    pets: "None",
    notes: "Corporate lawyer, uses second bedroom as office. Pays rent quarterly in advance. Excellent tenant.",
    address: "Unit 415, Your Building",
    employer: "Perkins Coie",
    moveReason: "Job Relocation"
  },
  {
    name: "Brian Martinez",
    email: "bmartinez.fitness@gmail.com",
    phone: "(425) 555-0267",
    status: "Approved",
    moveInDate: "2025-02-01",
    unitType: "1 Bedroom",
    occupants: 2,
    pets: "1 small dog",
    notes: "Personal trainer and partner (yoga instructor). Need parking for work van. Have a French Bulldog.",
    address: "2345 Fitness Way, Kirkland, WA 98034",
    employer: "24 Hour Fitness",
    moveReason: "Closer to Work"
  },
  {
    name: "Sophia Nguyen",
    email: "snguyen.design@creative.com",
    phone: "(206) 555-0278",
    status: "New Inquiry",
    moveInDate: "2025-05-01",
    unitType: "Studio",
    occupants: 1,
    pets: "2 guinea pigs",
    notes: "Graphic designer, works from home. Needs high-speed internet confirmation. Has two guinea pigs in small habitat.",
    address: "6789 Art District Ln, Seattle, WA 98103",
    employer: "Adobe (Remote)",
    moveReason: "First Time Renter"
  },
  {
    name: "Tom Anderson",
    email: "tanderson.pilot@airlines.com",
    phone: "(206) 555-0289",
    status: "Search Hold",
    moveInDate: "2025-06-01",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "None",
    notes: "Airline pilot with irregular schedule. Travels 15 days/month. Needs flexible lease and secure mail handling.",
    address: "4567 Airport Way, SeaTac, WA 98188",
    employer: "Alaska Airlines",
    moveReason: "Job Relocation"
  },
  {
    name: "Jessica & Mark Thompson",
    email: "thompson.family@email.com",
    phone: "(425) 555-0290",
    status: "Leased Elsewhere",
    moveInDate: "2025-01-15",
    unitType: "2 Bedroom",
    occupants: 3,
    pets: "1 cat, 1 dog",
    notes: "Young family with newborn. Chose property with on-site daycare. Were very interested but amenities didn't match.",
    address: "8901 Family Ct, Redmond, WA 98053",
    employer: "Microsoft / Amazon",
    moveReason: "Upsizing"
  },
  {
    name: "Carlos Mendez",
    email: "cmendez.chef@restaurant.com",
    phone: "(206) 555-0301",
    status: "Tour Completed",
    moveInDate: "2025-02-20",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Executive chef, works late hours. Needs quiet daytime environment for sleep. Very interested in top floor units.",
    address: "3210 Restaurant Row, Seattle, WA 98101",
    employer: "Canlis Restaurant",
    moveReason: "Closer to Work"
  },
  {
    name: "Hannah Lee",
    email: "hlee.nurse@medical.com",
    phone: "(206) 555-0312",
    status: "Contacted",
    moveInDate: "2025-03-01",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 elderly cat",
    notes: "ICU nurse working 12-hour shifts. Needs quiet neighbors. Has 15-year-old cat requiring special care.",
    address: "5432 Healthcare Ave, Seattle, WA 98104",
    employer: "Virginia Mason",
    moveReason: "Downsizing"
  },
  {
    name: "Richard Chang",
    email: "rchang.professor@uw.edu",
    phone: "(206) 555-0323",
    status: "Application Submitted",
    moveInDate: "2025-01-25",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "None",
    notes: "University professor on sabbatical. Needs 6-month lease option. Wife is visiting researcher from Japan.",
    address: "6543 Academic Way, Seattle, WA 98195",
    employer: "University of Washington",
    moveReason: "Other"
  },
  {
    name: "Natalie Brooks",
    email: "nbrooks.artist@studio.com",
    phone: "(206) 555-0334",
    status: "New Inquiry",
    moveInDate: "2025-04-15",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "3 fish tanks",
    notes: "Professional artist with home gallery. Needs permission for wall mounting. Has three large aquariums (100+ gallons total).",
    address: "7654 Gallery District, Seattle, WA 98102",
    employer: "Self-Employed Artist",
    moveReason: "Other"
  },
  {
    name: "Steve Johnson",
    email: "sjohnson.contractor@build.com",
    phone: "(425) 555-0345",
    status: "Tour Scheduled",
    moveInDate: "2025-02-10",
    unitType: "3 Bedroom",
    occupants: 5,
    pets: "1 service dog",
    notes: "General contractor with family of 5. Oldest child has service dog for autism support. Needs ADA compliant unit.",
    address: "8765 Construction Blvd, Bellevue, WA 98006",
    employer: "Johnson Construction LLC",
    moveReason: "Upsizing"
  },
  {
    name: "Olivia Smith",
    email: "osmith.therapist@wellness.com",
    phone: "(206) 555-0356",
    status: "Approved",
    moveInDate: "2025-01-30",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Mental health therapist seeing remote clients. Needs excellent soundproofing for confidentiality.",
    address: "9876 Wellness Center Dr, Seattle, WA 98115",
    employer: "Private Practice",
    moveReason: "Downsizing"
  },
  {
    name: "William Brown",
    email: "wbrown.veteran@mil.com",
    phone: "(206) 555-0367",
    status: "Leased",
    moveInDate: "2024-10-01",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 therapy dog",
    notes: "Military veteran with PTSD therapy dog. Quiet, reliable tenant. Pays with VA housing voucher.",
    address: "Unit 201, Your Building",
    employer: "Boeing (Veteran Program)",
    moveReason: "Job Relocation"
  },
  {
    name: "Emma Davis",
    email: "edavis.teacher@schools.edu",
    phone: "(425) 555-0378",
    status: "Search Hold",
    moveInDate: "2025-08-01",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "2 cats",
    notes: "Elementary teacher waiting for school year to end. Partner is firefighter. Need lease to start in August.",
    address: "1098 Education Lane, Kirkland, WA 98033",
    employer: "Lake Washington School District",
    moveReason: "Closer to Work"
  },
  {
    name: "Noah Williams",
    email: "nwilliams.engineer@auto.com",
    phone: "(206) 555-0389",
    status: "Contacted",
    moveInDate: "2025-02-05",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 hedgehog",
    notes: "Automotive engineer with classic car hobby. Needs extra storage/garage space. Has pet hedgehog.",
    address: "2109 Motor Ave, Seattle, WA 98108",
    employer: "Tesla Service Center",
    moveReason: "Other"
  },
  {
    name: "Isabella Garcia",
    email: "igarcia.dental@smile.com",
    phone: "(206) 555-0390",
    status: "Tour Completed",
    moveInDate: "2025-03-10",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "None",
    notes: "Dentist opening new practice nearby. Partner is accountant. Both have excellent credit, looking for long-term lease.",
    address: "3210 Dental Plaza, Seattle, WA 98105",
    employer: "Bright Smile Dental",
    moveReason: "Closer to Work"
  },
  {
    name: "Mason Taylor",
    email: "mtaylor.filmmaker@media.com",
    phone: "(206) 555-0401",
    status: "New Inquiry",
    moveInDate: "2025-02-25",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "None",
    notes: "Documentary filmmaker, travels frequently for shoots. Needs unit suitable for equipment storage and occasional editing.",
    address: "4321 Film Studio Way, Seattle, WA 98103",
    employer: "Freelance Filmmaker",
    moveReason: "Downsizing"
  },
  {
    name: "Ava Martinez",
    email: "amartinez.biotech@research.com",
    phone: "(425) 555-0412",
    status: "Application Submitted",
    moveInDate: "2025-01-28",
    unitType: "Studio",
    occupants: 1,
    pets: "None",
    notes: "Biotech researcher working on PhD. Needs quiet study environment. Has full scholarship covering housing.",
    address: "5432 Research Park, Bothell, WA 98011",
    employer: "Fred Hutchinson Cancer Center",
    moveReason: "First Time Renter"
  },
  {
    name: "Ethan Anderson",
    email: "eanderson.sports@team.com",
    phone: "(206) 555-0423",
    status: "Leased Elsewhere",
    moveInDate: "2025-01-20",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "1 large dog",
    notes: "Professional athlete, signed with competitor offering gym facilities. Was interested but needed specific amenities.",
    address: "6543 Stadium Way, Seattle, WA 98134",
    employer: "Seattle Sounders FC",
    moveReason: "Job Relocation"
  },
  {
    name: "Sophie Roberts",
    email: "sroberts.architect@design.com",
    phone: "(206) 555-0434",
    status: "Tour Scheduled",
    moveInDate: "2025-02-18",
    unitType: "1 Bedroom",
    occupants: 1,
    pets: "1 rabbit",
    notes: "Architect appreciates good design, interested in newer units. Works from home 2 days/week. Has a Holland Lop rabbit.",
    address: "7654 Design District, Seattle, WA 98101",
    employer: "NBBJ Architecture",
    moveReason: "Closer to Work"
  },
  {
    name: "Lucas White",
    email: "lwhite.pharmacist@rx.com",
    phone: "(425) 555-0445",
    status: "Approved",
    moveInDate: "2025-02-03",
    unitType: "2 Bedroom",
    occupants: 2,
    pets: "2 small birds",
    notes: "Pharmacist and partner (physical therapist). Both work at same medical complex. Have two parakeets.",
    address: "8765 Medical Complex Dr, Bellevue, WA 98004",
    employer: "Walgreens / ATI Physical Therapy",
    moveReason: "Closer to Work"
  }
];

export async function seedDatabase() {
  console.log("Starting database seed...");
  
  for (const lead of sampleLeads) {
    try {
      const docRef = await addDoc(collection(db, 'leads'), lead);
      console.log(`✓ Added ${lead.name} with ID: ${docRef.id}`);
    } catch (error) {
      console.error(`✗ Error adding ${lead.name}:`, error);
    }
  }
  
  console.log("Database seeding complete! Added " + sampleLeads.length + " leads.");
}

// // Uncomment the line below to run the seed when this file is imported


